### ISSUE TITLE
Issue with clients not having server-resource-packs folder.

### ISSUE THREAD

**Issue by semmeess** [Maximvdw/ArcadeBoard-API#2]
If a client does not have the server-resource-packs directory present in their appdata/.minecraft (whatever it is) folder, then the plugin crashes their client when it attempts to send the resource pack.

https://i.imgur.com/Vdr3Mr0.png

Could you release versions of the games which use ascii squares or something similar instead? Or do you know any way to solve this issue? Thanks.

**Comment by Maximvdw** [comment]
Hello,

Unfortunately this is not an issue I can fix. It has been fixed in the latest launch ers (2015) and works on 1.8.x as well.

This means the players are using a very old launcher
https://bugs.mojang.com/plugins/servlet/mobile#issue/MCL-3732

- Maxim

**Comment by Maximvdw** [comment]
Simply updating the launcher should fix the issue
