### ISSUE TITLE
Resource pack hosting

### ISSUE THREAD

**Issue by gp-Airee** [Maximvdw/ArcadeBoard-API#4]
Where are the resource packs hosted? Can the server admin change it to something other than your provided host?

**Comment by Maximvdw** [comment]
Resource packs are uploaded to Minepack and MCPacks as a failback if the first one is down.

Currently it can not be changed to your own host. The reason for this was to make the configuration as easy as possible. Minecraft is very strict in handling resource packs, therefor I decided on tested hosts to host the automatically generated packs.

**Comment by Maximvdw** [comment]
Fyi:
https://mc-packs.net
https://minepack.net/

**Comment by gp-Airee** [comment]
well uh, I don't want to use mc-packs. Can you allow for usage of own servers?
